<a href="https://colab.research.google.com/github/IsmaMunoz/Pandas_numpy/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

Importar libreria numpy

In [ ]:
import numpy as np

Definir la lista

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista

Volvemos la lista un array

In [ ]:
arr = np.array(lista)
arr

Una matriz son varios Vectores o listas agrupadas una encima de la otra, es como una tabla de Excel

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

In [ ]:
arr[0]

1

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [ ]:
matriz [0]

array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Nota: El primer elemento selecciona las filas, el segundo elemento las columnas

In [ ]:
matriz[0, 2]

3

Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5.

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

Si no se ingresa el valor de inicio, se toma el inicio como la posición 0.

In [ ]:
arr [:6]

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array.

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [ ]:
arr[-1]

9

In [ ]:
arr[-3:]

array([7, 8, 9])