<a href="https://colab.research.google.com/github/IsmaMunoz/Pandas_numpy/blob/main/Dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
scalar = np.array (42)
print (scalar)
scalar.ndim

42


0

In [5]:
vector = np.array ([42,45,67])
print (vector)
scalar.ndim

[42 45 67]


0

In [8]:
matriz = np.array ([[42,45,67],[48,87,89]])
print (matriz)
matriz.ndim

[[42 45 67]
 [48 87 89]]


2

In [12]:
tensor = np.array ([[[42,45,67],[48,87,89]],[[1,2,3],[4,5,6]]])
print (tensor)
tensor.ndim

[[[42 45 67]
  [48 87 89]]

 [[ 1  2  3]
  [ 4  5  6]]]


3